name: R package check

on:
  push:
    branches: [main]
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v1
      with:
        r-version: '4.1.0'
    - name: Install dependencies
      run: R -e 'install.packages(c("devtools", "testthat"))'
    - name: Check package
      run: R -e 'devtools::check(); message("Check complete!")'
