name: Check Package
on: [push, pull_request]
jobs:
  check:
    runs-on: macOS-latest
    strategy:
      matrix:
        r-version: [4.0.5]
    steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v1
      with:
        r-version: ${{ matrix.r-version }}
    #- name: Install dependencies
    #  run: Rscript -e 'devtools::install_deps()'
    #- name: Check package
    #  run: Rscript -e 'devtools::check()'
